/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCat: typeof import('./components/addCat.vue')['default']
    CatAlbum: typeof import('./components/catAlbum.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModifyCatInfo: typeof import('./components/modifyCatInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
